### PR TITLE
test_utils updated.

### PR DESCRIPTION
**Pull request by ryanhammonds**
Utils tests to 98% coverage.

### CODE REVIEW

**Comment by dPys** [comment]
Hey @ryanhammonds I'm looking through the PR right now.

Would you be able to figure out where/why [travis](https://travis-ci.org/dPys/PyNets/jobs/654285602?utm_medium=notification&utm_source=github_status) is failing, adjust the test(s), and then force-push your changes to update this PR?

**Comment by ryanhammonds** [comment]
Hi @dPys, I'll dig into this tonight. The tests are dependent on files in tests/examples, which isn't included in the development branch. Do you think this may be the issue?

**Comment by dPys** [comment]
> Hi @dPys, I'll dig into this tonight. The tests are dependent on files in tests/examples, which isn't included in the development branch. Do you think this may be the issue?

Could be. Maybe try swapping out the examples dir that you have with a fresh one that travis is pulling from? You could re-download it with:
`wget --retry-connrefused --waitretry=5 --read-timeout=20 --timeout=15 -t 0 -q -O examples.tar.gz "https://osf.io/aq8ur/download"`
` tar -xvzf examples.tar.gz -C PyNets/tests`

**Comment by ryanhammonds** [comment]
The issue was with test_pass_meta_outs that called netmotifs.build_multigraphs. I fixed it by xfailing that test.

First it was an index error, then it was a import py3plex error (it is commented in requirements.txt), then a import error for a missing py3plex dependency that is not installed with py3plex, then it was a pandas attribute error that I wasn’t seeing locally. 

I fixed these errors as I went, but after the fourth error, I figured it was a job for testing netmotifs instead.

**Comment by dPys** [comment]
Looks perfect now! Merging now and re-running codecov to see where this gets us overall. My sense is we're about 1-2 months away from a 1.0 stable release...

**Pull request merged**
